# Configuration for the E-commerce Churn Prediction Project

# File paths
data_paths:
  raw_data: "data/raw/ecommerce_churn_data.csv"
  processed_data: "data/processed/processed_data.csv"
  train_data: "data/processed/train.csv"
  test_data: "data/processed/test.csv"

model_paths:
  model_output_dir: "saved_models/"
  preprocessor_filename: "saved_models/preprocessor.pkl"

# Directory for saving evaluation reports
reports_path: "reports/"

# Model parameters
model_params:
  target_column: "Churn"
  test_size: 0.2
  random_state: 42
  # Parameters for RandomForest
  random_forest:
    n_estimators: 150
    max_depth: 10
    min_samples_split: 5

# MLflow configuration for experiment tracking
mlflow:
  tracking_uri: "mlruns" # This creates a local directory to store experiments
  experiment_name: "ECommerce Churn Prediction"